FROM golang:1.25-alpine AS builder

ARG VERSION=dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-X main.Version=${VERSION}" -o /squash-games-management ./cmd/squash-games-management/main.go


FROM alpine:3.18

RUN apk --no-cache add ca-certificates tzdata wget

WORKDIR /app

COPY --from=builder /squash-games-management .

CMD ["./squash-games-management"]
